name: build
on: [push]

jobs:
  build-app:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx

    env:
      CMAKE_BUILD_DIR: "${{ github.workspace }}/build"
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - name: Install Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq cmake build-essential gcc-multilib
          sudo apt-get install -y -qq mesa-common-dev mesa-utils freeglut3-dev ninja-build \
                                  libavcodec-dev libavformat-dev libavutil-dev libboost-dev \
                                  libdouble-conversion-dev libeigen3-dev libexpat1-dev libfontconfig-dev \
                                  libfreetype6-dev libgdal-dev libglew-dev libhdf5-dev libjpeg-dev libjsoncpp-dev \
                                  liblz4-dev liblzma-dev libnetcdf-dev libnetcdf-cxx-legacy-dev libogg-dev \
                                  libpng-dev libpython3-dev libqt5opengl5-dev libqt5x11extras5-dev libsqlite3-dev \
                                  libswscale-dev libtheora-dev libtiff-dev libxml2-dev libxt-dev qtbase5-dev \
                                  qttools5-dev zlib1g-dev

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.1.0"
          ubuntu-version: "16.04"
          force-version: true
          directory: ${{ runner.temp }}/llvm

      - name: Install vtk
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              git clone --recursive https://gitlab.kitware.com/vtk/vtk.git
              cd vtk
              git checkout v9.0.1
              mkdir build
              cd build
              cmake -DCMAKE_INSTALL_PREFIX=$HOME/vtk-inst \
                    -DCMAKE_INSTALL_RPATH=$HOME/vtk-inst \
                    -DVTK_Group_Qt=ON \
                    -DVTK_QT_VERSION=5 \
                    -DVTK_Group_Imaging=ON \
                    -DVTK_Group_Views=ON \
                    -DModule_vtkRenderingFreeTypeFontConfig=ON \
                    -DBUILD_TESTING=OFF \
                    -DVTK_USE_SYSTEM_LIBRARIES=ON \
                    -DVTK_USE_SYSTEM_LIBPROJ4=OFF \
                    -DVTK_USE_SYSTEM_GL2PS=OFF \
                    -DVTK_USE_SYSTEM_LIBHARU=OFF \
                    -DVTK_USE_SYSTEM_PUGIXML=OFF \
                    -DCMAKE_BUILD_TYPE=Release \
                    ..
              make -j$(($(nproc) - 1))
              make install
          elif [ "$RUNNER_OS" == "macOS" ]; then
              brew install vtk
          else
              echo "$RUNNER_OS not supported"
              exit 1
          fi
        shell: bash

      - name: llvm version check
        run: clang --version

      - name: Cmake version
        run: cmake --version

      - name: CMake
        run: cmake .

      - name: Make
        run: make

      - name: Run Test
        run: make test
