name: build
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq cmake build-essential gcc-multilib
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.1.0"
          ubuntu-version: "16.04"
          force-version: true
          directory: ${{ runner.temp }}/llvm
      - name: llvm version check
        run: clang --version
      - name: Cmake version
        run: cmake --version
      - name: CMake
        run: cmake .
      - name: Make
        run: make
